# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f76d38a69dc52ae7911735f2cab64720f31e1943942ca963b329819778ec44cc19359381cf4228568f8bf283b1862f9f691e36db1ca57dab253c20caec1d3a7

test:
  secret_key_base: b5001868290122cb90860a6882e5cebdd5ee30f7307cb490c64099e5dd8a50f54bdc1022599c63562335def3ff063a628601ef15c3fe7afc43d07ed8decaf7b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
